### ISSUE TITLE
为什么执行 sudo wechattweak-cli --install

### ISSUE THREAD

**Issue by LAnqxpp** [Sunnyyoung/WeChatTweak-CLI#12]
就报错 您没有权限打开应用程序 微信

**Comment by LAnqxpp** [comment]
wangweichao@wangweihaodeMBP ~ % sudo /Users/wangweichao/Desktop/WeChatTweak-CLI-master --install
Password:
sudo: /Users/wangweichao/Desktop/WeChatTweak-CLI-master: command not found
wangweichao@wangweihaodeMBP ~ % sudo wechattweak-cli --install
------ Backup ------
Created WeChat.bak...
------ Download ------
------ Unzip ------
Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS
------ Insert Dylib ------
Binary is a fat binary with 2 archs.
LC_CODE_SIGNATURE load command found. Remove it.
LC_CODE_SIGNATURE load command found. Remove it.
Added LC_LOAD_DYLIB to all archs in /Applications/WeChat.app/Contents/MacOS/WeChat
------ Codesign ------
Execute command: cp /Applications/WeChat.app/Contents/MacOS/WeChat /tmp/WeChat
Execute command: codesign --force --deep --sign - /tmp/WeChat
Execute command: cp /tmp/WeChat /Applications/WeChat.app/Contents/MacOS/WeChat
Install success!

**Comment by mokery** [comment]
今天apple store正式版新版更新了，然后安装完成，打不开，卸载就有可以打开了

**Comment by muchao** [comment]
嗯 我也安装新版本后 重新安装就打不开了 uninstall后就正常了 但是没了插件功能  耐心等大佬更新吧

**Comment by muchao** [comment]
看了close的issues 先uninstall 再install 再不行重启 应该就可以了  我的已经正常了

**Comment by Sunnyyoung** [comment]
1. 卸载再安装
2. 重启电脑

基本都可以解决了
