### ISSUE TITLE
程序还会更新吗？目前失效

### ISSUE THREAD

**Issue by louischanz** [Sunnyyoung/WeChatTweak-CLI#13]
苹果商店微信版本3.2.2，当install之后微信就无法打开，重装也一样

**Comment by Sunnyyoung** [comment]
正常使用中，有空就更新，你重启电脑试试

**Comment by ghl116** [comment]
> 苹果商店微信版本3.2.2，当install之后微信就无法打开，重装也一样
不要乱升级，我的微信版本是3.2.1，可以正常使用，试了好多次才装上

**Comment by ghl116** [comment]
@louischanz  不要乱升级，我的微信版本是3.2.1，可以正常使用，试了好多次才装上
