### ISSUE TITLE
安装不成功

### ISSUE THREAD

**Issue by 495696116** [Sunnyyoung/WeChatTweak-CLI#16]
可否出个简单操作过程
![image](https://user-images.githubusercontent.com/41635121/151479381-2ac36b5a-d5cd-4ab3-97b1-5adfadf21114.png)

**Comment by Sunnyyoung** [comment]
https://github.com/Sunnyyoung/WeChatTweak-CLI#usage

这里说得很清楚了，`sudo wechattweak-cli --install`

**Comment by 495696116** [comment]
![Uploading D0949E72-E05D-479E-A743-EEC1BC7DCED6.png…]()
谢谢，请问一下，这个成功之后，微信提示无法打开怎么办？

**Comment by 495696116** [comment]
谢谢，已经安装OK
