### ISSUE TITLE
样式问题

### ISSUE THREAD

**Issue by bydongxing** [Sunnyyoung/WeChatTweak-CLI#18]
![image](https://user-images.githubusercontent.com/32316182/153372791-c3ab64fc-8621-4651-9f3c-2b54fe3c922f.png)

微信防撤回，样式问题，使用的是  **wechattweak-cli: 1.3** 版本

**Comment by Sunnyyoung** [comment]
WeChatTweak 用的是 1.2.5 版本吗？

**Comment by bydongxing** [comment]
我是通过 brew 的方式安装的。图片中是 wechattweak-cli 的信息
![image](https://user-images.githubusercontent.com/32316182/153379912-2b4d1e4a-1d16-42f2-870b-d4908e10bfb9.png)

**Comment by Sunnyyoung** [comment]
```bash
cat /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework/Versions/A/Resources/Info.plist
```

看看 CFBundleShortVersionString 是多少

**Comment by bydongxing** [comment]
![image](https://user-images.githubusercontent.com/32316182/153381681-9f4e0008-af4e-4df0-b801-eb9c398bc520.png)

**Comment by Sunnyyoung** [comment]
执行 `sudo wechattweak-cli install` 更新下吧，1.2.3 是旧版本，更新完重启微信。

**Comment by bydongxing** [comment]
好的，现在更新到 1.2.5了，但是有个问题想请教下，现在撤回的消息，没有撤回的消息样式了吗？
![image](https://user-images.githubusercontent.com/32316182/153382683-c6b54b59-c3d4-4f36-a602-21d9946fce5e.png)

**Comment by Sunnyyoung** [comment]
有的，你是群聊还是单聊

**Comment by bydongxing** [comment]
单聊

**Comment by Sunnyyoung** [comment]
<img width="283" alt="image" src="https://user-images.githubusercontent.com/5926284/153390193-5df37510-10a6-4f6f-ae91-21cf729f6172.png">

没有复现

**Comment by bydongxing** [comment]
重启后，一切正常了，谢谢
