### ISSUE TITLE
微信3.3.0版本貌似用不了这个插件了

### ISSUE THREAD

**Issue by neo-6** [Sunnyyoung/WeChatTweak-CLI#21]
sudo xattr -d com.apple.quarantine /Appli
cations/WeChat.app
会提示：
xattr: /Applications/WeChat.app: No such xattr: com.apple.quarantine

tweak使用的1.3版本
wechat版本是3.3.0

**Comment by dreamingchow** [comment]
自动更新微信3.3.1，也用不了了。报错如下：
------ Download ------
------ Unzip ------
Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS
------ Backup ------
Created WeChat.bak...
------ Remove Codesign ------
Execute command: codesign --remove-sign /Applications/WeChat.app/Contents/MacOS/WeChat
------ Insert Dylib ------
Binary is a fat binary with 2 archs.
It doesn't seem like there is enough empty space. Continue anyway.Added LC_LOAD_DYLIB to all archs in /Applications/WeChat.app/Contents/MacOS/WeChat
------ Add Codesign ------
Execute command: codesign --force --deep --sign - /Applications/WeChat.app/Contents/MacOS/WeChat
Install failed: Execute command: codesign --force --deep --sign - /Applications/WeChat.app/Contents/MacOS/WeChat failed: {
    NSAppleScriptErrorAppName = "wechattweak-cli";
    NSAppleScriptErrorBriefMessage = "/Applications/WeChat.app/Contents/MacOS/WeChat: internal error in Code Signing subsystem";
    NSAppleScriptErrorMessage = "/Applications/WeChat.app/Contents/MacOS/WeChat: internal error in Code Signing subsystem";
    NSAppleScriptErrorNumber = 1;
    NSAppleScriptErrorRange = "NSRange: {0, 97}";
}

**Comment by imruxin** [comment]
我也遇到这个问题了 @dreamingchow 
我的微信版本是 Version. 3.3.1 (21164)

**Comment by yyyy777** [comment]
我也是 有解决办法了吗？

**Comment by dreamingchow** [comment]
去官网下载（显示3.3.0），安装后是3.3.1，然后就能正常安装tweak

**Comment by benniuxj** [comment]
方法有效！
App Version: Version. 3.3.1 (21163)
System: OSX 12.3 build(21E230)
Model: MacBookPro15,2
Build Date: Mar 14 2022
Build Time: 11:39:26
Lang: zh-Hans-CN

**Comment by yyyy777** [comment]
> 去官网下载（显示3.3.0），安装后是3.3.1，然后就能正常安装tweak

确实可以了 牛啊 兄弟

**Comment by cikichen** [comment]
> 去官网下载（显示3.3.0），安装后是3.3.1，然后就能正常安装tweak

可用

**Comment by likaozheng** [comment]
> 去官网下载（显示3.3.0），安装后是3.3.1，然后就能正常安装tweak

可行，赞一个！

**Comment by mr-dragon** [comment]
设备类型：MacBookPro17,1
系统版本：版本11.6（版号20G165）
微信版本：[2022-03-14 11:40:38] v3.3.1.18 (21163) #576c5ed0f6 p_0
历史版本：[2022-03-18 10:34:13] v3.3.1.16 (21164) #97d5f1d11b
可以安装，但是自己发消息给小号撤回无效
@Sunnyyoung

**Comment by Sunnyyoung** [comment]
@mr-dragon 自己发出的消息是正常撤回没错，我试了提示是正常

**Comment by mr-dragon** [comment]
> 

![image](https://user-images.githubusercontent.com/25114117/158932266-15a50ced-9b49-4dad-8720-dea355cfa039.png)
又好了，可以重启了微信，我看评论去说重启，谢谢大佬解答，祝**万事顺意**

**Comment by Sunnyyoung** [comment]
https://github.com/Sunnyyoung/WeChatTweak-macOS/issues/457
