### ISSUE TITLE
Codesign failed

### ISSUE THREAD

**Issue by isyntop** [Sunnyyoung/WeChatTweak-CLI#24]
通过app store更新微信之后，重新安装就报错了。

$ sudo wechattweak-cli install
------ Download ------
------ Unzip ------
Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS
------ Backup ------
Created WeChat.bak...
------ Remove Codesign ------
Execute command: codesign --remove-sign /Applications/WeChat.app/Contents/MacOS/WeChat
------ Insert Dylib ------
Binary is a fat binary with 2 archs.
It doesn't seem like there is enough empty space. Continue anyway.Added LC_LOAD_DYLIB to all archs in /Applications/WeChat.app/Contents/MacOS/WeChat
------ Add Codesign ------
Execute command: codesign --force --deep --sign - /Applications/WeChat.app/Contents/MacOS/WeChat
Install failed: Execute command: codesign --force --deep --sign - /Applications/WeChat.app/Contents/MacOS/WeChat failed: {
    NSAppleScriptErrorAppName = "wechattweak-cli";
    NSAppleScriptErrorBriefMessage = "/Library/Developer/CommandLineTools/usr/bin/codesign_allocate: for architecture x86_64 object: /Applications/WeChat.app/Contents/MacOS/WeChat malformed object (offset field of section 0 in LC_SEGMENT command 1 not past the hea/Applications/WeChat.app/Contents/MacOS/WeChat: the codesign_allocate helper tool cannot be found or used";
    NSAppleScriptErrorMessage = "/Library/Developer/CommandLineTools/usr/bin/codesign_allocate: for architecture x86_64 object: /Applications/WeChat.app/Contents/MacOS/WeChat malformed object (offset field of section 0 in LC_SEGMENT command 1 not past the headers /Applications/WeChat.app/Contents/MacOS/WeChat: the codesign_allocate helper tool cannot be found or used";
    NSAppleScriptErrorNumber = 1;
    NSAppleScriptErrorRange = "NSRange: {0, 97}";
}

**Comment by dreamingchow** [comment]
去官网下载

**Comment by isyntop** [comment]
<img width="459" alt="image" src="https://user-images.githubusercontent.com/20900723/159427213-1c0437e7-883e-4d54-8060-715bbd2c1c91.png">

**Comment by Sunnyyoung** [comment]
https://github.com/Sunnyyoung/WeChatTweak-macOS/issues/457

**Comment by sarkrui** [comment]
M1 Macbook Air, OS 12.3, 亲测安装 MAS 最新版本再安装 WeChatTweak 会出现无打开权限的问题。改用官网版 [传送门](https://dldir1.qq.com/weixin/mac/WeChatMac.dmg) 替换安装，再重新执行以下安装命令就行了！
```
brew upgrade wechattweak-cli && sudo wechattweak-cli install
```
