### ISSUE TITLE
用brew安装，失败。。

### ISSUE THREAD

**Issue by kvk-258** [Sunnyyoung/WeChatTweak-CLI#25]
==> Tapping sunnyyoung/repo
Cloning into '/usr/local/Homebrew/Library/Taps/sunnyyoung/homebrew-repo'...
fatal: unable to access 'https://github.com/sunnyyoung/homebrew-repo/': LibreSSL SSL_connect: Connection reset by peer in connection to github.com:443 
Error: Failure while executing; `git clone https://github.com/sunnyyoung/homebrew-repo /usr/local/Homebrew/Library/Taps/sunnyyoung/homebrew-repo --origin=origin --template=` exited with 128.
huangxindeMacBook-Pro:~ huangxin$ sudo wechattweak-cli install
Password:
sudo: wechattweak-cli: command not found
huangxindeMacBook-Pro:~ huangxin$ brew install sunnyyoung/repo/wechattweak-cli
==> Tapping sunnyyoung/repo
Cloning into '/usr/local/Homebrew/Library/Taps/sunnyyoung/homebrew-repo'...
fatal: unable to access 'https://github.com/sunnyyoung/homebrew-repo/': LibreSSL SSL_connect: Connection reset by peer in connection to github.com:443 
Error: Failure while executing; `git clone https://github.com/sunnyyoung/homebrew-repo /usr/local/Homebrew/Library/Taps/sunnyyoung/homebrew-repo --origin=origin --template=` exited with 128.

**Comment by Sunnyyoung** [comment]
网络问题

**Comment by kvk-258** [comment]
> 网络问题

换了几次网络都是这样，直接芭比Q。。

**Comment by kvk-258** [comment]
今天又重新试了一下，已经安装成功了，感谢
