### ISSUE TITLE
安装成功为什么不显示

### ISSUE THREAD

**Issue by LAnqxpp** [Sunnyyoung/WeChatTweak-CLI#26]

**Comment by Sunnyyoung** [comment]
不显示什么

**Comment by LAnqxpp** [comment]
Last login: Fri Mar 25 20:00:41 on ttys000
wangweichao@wangweichaodeMacBook-Pro ~ % brew install sunnyyoung/repo/wechattweak-cli
Warning: Cask 'wechattweak-cli' is already installed.

To re-install wechattweak-cli, run:
  brew reinstall wechattweak-cli
wangweichao@wangweichaodeMacBook-Pro ~ % brew reinstall wechattweak-cli
==> Downloading https://github.com/Sunnyyoung/WeChatTweak-CLI/releases/download/
Already downloaded: /Users/wangweichao/Library/Caches/Homebrew/downloads/155247a4046f7264d77cea457845b077fadc42563558c84d103e908cfb99bdbb--wechattweak-cli
==> Uninstalling Cask wechattweak-cli
==> Unlinking Binary '/usr/local/bin/wechattweak-cli'
==> Purging files for version 1.3 of Cask wechattweak-cli
==> Installing Cask wechattweak-cli
==> Linking Binary 'wechattweak-cli' to '/usr/local/bin/wechattweak-cli'
🍺  wechattweak-cli was successfully installed!
为什么不显示 防撤回 工具

**Comment by LAnqxpp** [comment]
Version. 3.3.1 (21164)  App商店版本

**Comment by Sunnyyoung** [comment]
再认真看看文档？

**Comment by LAnqxpp** [comment]
我看了几个说是要在官网下载 下载是3.3.0 也那样安装不对，难道是我少步骤了

**Comment by Sunnyyoung** [comment]
`sudo wechattweak-cli install` 你执行了？

**Comment by wyshp** [comment]
我也遇到同样问题（官网下载的微信版本： 3.3.1 (21163)），重启微信任无法显示撤回软件，不知道什么情况

**Comment by LAnqxpp** [comment]
> `sudo wechattweak-cli install` 你执行了？

今天突然执行了一次好了，神奇很

**Comment by LAnqxpp** [comment]
> 我也遇到同样问题（官网下载的微信版本： 3.3.1 (21163)），重启微信任无法显示撤回软件，不知道什么情况

按步骤你在操作一遍，我今天弄了 好了
