### ISSUE TITLE
3.4.0 (21712) Beta 11已经失效

### ISSUE THREAD

**Issue by lnzoro** [Sunnyyoung/WeChatTweak-CLI#28]
蒙特雷12。3。1 微信最新版失效了，打不开

**Comment by Sunnyyoung** [comment]
<img width="590" alt="image" src="https://user-images.githubusercontent.com/5926284/163739493-7cf53a80-ffbb-401b-ad1b-60812901ac41.png">

**Comment by lnzoro** [comment]
1.4的版本没问题
