### ISSUE TITLE
在mac OS 12.3.1 上，微信3.4 显示打开错误

### ISSUE THREAD

**Issue by wupuyuan** [Sunnyyoung/WeChatTweak-CLI#29]
在mac OS 12.3.1 上，微信3.4 显示打开错误。
重新签名过，但是问题依然存在。

**Comment by Sunnyyoung** [comment]
<img width="590" alt="image" src="https://user-images.githubusercontent.com/5926284/163739472-ff3c77e8-4063-46d8-bb0e-32126d41c69b.png">

你描述下你的安装流程

**Comment by wupuyuan** [comment]
我是先安装过WeChatTweak的。
1. 升级wechat
2. 卸载了WeChatTweak。sudo wechattweak-cli uninstall
3. 重新安装、更新WeChatTweak 
`brew install sunnyyoung/repo/wechattweak-cli
brew upgrade wechattweak-cli --cask
`
4. 安装WeChatTweak sudo wechattweak-cli install
打开后显示失败，
两个重置签名的命令都试用了下：
codesign -dvvv /Applications/WeChat.app
codesign --force --deep --sign - /Applications/WeChat.app/Contents/MacOS/WeChat
结果还是失败。

**Comment by Sunnyyoung** [comment]
```bash
brew update wechattweak-cli
sudo wechattweak-cli install
```

最好重启电脑

**Comment by wupuyuan** [comment]
我试一试

**Comment by wupuyuan** [comment]
执行了两行命令并重启，但是问题依然存在
`brew upgrade wechattweak-cli
sudo wechattweak-cli install`
错误信息：{"app_name":"WeChat","timestamp":"2022-04-18 09:51:37.00 +0800","app_version":"3.4.0.17","slice_uuid":"5c1fd439-9c7f-3f39-b9ee-a9b9f4e3f1de","build_version":"21712","platform":1,"bundleID":"com.tencent.xinWeChat","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.3.1 (21E258)","incident_id":"B26CFFFE-DEB3-4D42-9725-CDB050B5DB1E","name":"WeChat"}

<img width="260" alt="image" src="https://user-images.githubusercontent.com/7089112/163742208-3b979950-8caa-4d15-ac27-7eaccdbb4927.png">

**Comment by WayChan** [comment]
> 执行了两行命令并重启，但是问题依然存在 `brew upgrade wechattweak-cli` `sudo wechattweak-cli install` 错误信息：{"app_name":"WeChat","timestamp":"2022-04-18 09:51:37.00 +0800","app_version":"3.4.0.17","slice_uuid":"5c1fd439-9c7f-3f39-b9ee-a9b9f4e3f1de","build_version":"21712","platform":1,"bundleID":"com.tencent.xinWeChat","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.3.1 (21E258)","incident_id":"B26CFFFE-DEB3-4D42-9725-CDB050B5DB1E","name":"WeChat"}
> 
> <img alt="image" width="260" src="https://user-images.githubusercontent.com/7089112/163742208-3b979950-8caa-4d15-ac27-7eaccdbb4927.png">

遭遇了相同问题，系统版本同12.3.1，iMac跟MBP都碰上了

**Comment by alterem** [comment]
安装没有问题，可是撤回没有了提示

**Comment by marnon7** [comment]
新安装，也是这个问题，安装其他issue里说的从官网下载了wx安装包覆盖安装了也是这样。

**Comment by Sunnyyoung** [comment]
[1.3.1](https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/tag/1.3.1)

**Comment by wupuyuan** [comment]
已经升级，解决！
