### ISSUE TITLE
Insert dylib failed 请问怎么处理？

### ISSUE THREAD

**Issue by iczrac** [Sunnyyoung/WeChatTweak-CLI#3]
------ Insert Dylib ------
/Applications/WeChat.app/Contents/MacOS/WeChat: No such file or directory
Install failed: Insert dylib failed

**Comment by Sunnyyoung** [comment]
删掉 WeChat.app 重装再试试？

**Comment by iczrac** [comment]
> 删掉 WeChat.app 重装再试试？

还是不行呢，然后打开微信也显示没有权限，要重新安装

**Comment by iczrac** [comment]
> > 删掉 WeChat.app 重装再试试？
> 
> 还是不行呢，然后打开微信也显示没有权限，要重新安装

可以了，第一次在appstore下载的不行，在网页下载的可以了，谢谢
