### ISSUE TITLE
我的也用不了。

### ISSUE THREAD

**Issue by benniuxj** [Sunnyyoung/WeChatTweak-CLI#30]
无法多开了。3.40.21712。我重装了老版本，又升级了。卸载了Tweak，重启，又重装了Tweak，又重启。始终不行
<img width="251" alt="截屏2022-04-18 16 55 59" src="https://user-images.githubusercontent.com/66509247/163784857-dd57dfaf-d3c7-49d1-ae4a-0d76da0f2a28.png">
<img width="682" alt="截屏2022-04-18 16 56 47" src="https://user-images.githubusercontent.com/66509247/163784886-23a894c9-21fa-47ee-9036-6d35790e3df7.png">
。

**Comment by benniuxj** [comment]
<img width="280" alt="截屏2022-04-18 17 15 17" src="https://user-images.githubusercontent.com/66509247/163786655-8dbda628-1cbe-4973-b1fe-59cffb5344ed.png">
不小心升级了操作系统。

**Comment by Sunnyyoung** [comment]
`sudo wechattweak-cli install`

**Comment by benniuxj** [comment]
谢谢，搞定了。谢谢！
