### ISSUE TITLE
1.3.1，通过homebrew安装成功后，微信里面还是没有tweak

### ISSUE THREAD

**Issue by 996WJC** [Sunnyyoung/WeChatTweak-CLI#31]
微信是最新的3.4.0，App Store更新的。
homebrew是运作正常的，运行的是：brew install sunnyyoung/repo/wechattweak-cli
显示安装成功，重启微信，发现tweak是没有的。
然后通过终端homebrew再reintall一次，安装成功，重启微信，同样，也是没有tweak。

Mac是15年的13寸pro，MacOS是最新的Monterey12.3.1

请大神帮个忙，看是哪个环节出错了，感谢！

**Comment by Sunnyyoung** [comment]
看文档，`sudo wechattweak-cli install` 执行了吗？

**Comment by Sunnyyoung** [comment]
另外建议使用官网版本，App Store 版本最近有点问题

**Comment by 996WJC** [comment]
> 

sudo wechattweak-cli install，这一条指令，是手动安装的时候，需要执行的。
如果我用的是homebrew，在安装过程中，哪个步骤中，需要执行这条指令？

**Comment by 996WJC** [comment]
Last login: Wed Apr 20 09:53:26 on ttys000
derekwu@derekwarddeMacBook-Pro ~ % brew install sunnyyoung/repo/wechattweak-cli
Error: 
  homebrew-core is a shallow clone.
  homebrew-cask is a shallow clone.
To `brew update`, first run:
  git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch --unshallow
  git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask fetch --unshallow
These commands may take a few minutes to run due to the large size of the repositories.
This restriction has been made on GitHub's request because updating shallow
clones is an extremely expensive operation due to the tree layout and traffic of
Homebrew/homebrew-core and Homebrew/homebrew-cask. We don't do this for you
automatically to avoid repeatedly performing an expensive unshallow operation in
CI systems (which should instead be fixed to not use shallow clones). Sorry for
the inconvenience!
==> Downloading https://github.com/Sunnyyoung/WeChatTweak-CLI/releases/download/
Already downloaded: /Users/derekwu/Library/Caches/Homebrew/downloads/9d54f57ae297194d208962f9f63880d63de94fbb97abfe74117cda57caa5f1ef--wechattweak-cli
==> Installing Cask wechattweak-cli
==> Linking Binary 'wechattweak-cli' to '/usr/local/bin/wechattweak-cli'
🍺  wechattweak-cli was successfully installed!
derekwu@derekwarddeMacBook-Pro ~ % 


刚刚重新在官网下载了微信，取代了App Store上面的微信，然后用homebrew安装了一次，打开微信后，还是不行。

**Comment by 996WJC** [comment]
> sudo wechattweak-cli install
可以了，感谢大神。

**Comment by Sunnyyoung** [comment]
wechattweak-cli 是安装工具，`sudo wechattweak-cli install` 是不可少的安装步骤。
