### ISSUE TITLE
The top menu bar is not displayed,but the function is normal

### ISSUE THREAD

**Issue by ddddict** [sunnyyoung/WeChatTweak-CLI#32]
------ Unzip ------
Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS
------ Backup ------
Created WeChat.bak...
------ Remove Codesign ------
Execute command: codesign --remove-sign /Applications/WeChat.app/Contents/MacOS/WeChat
------ Insert Dylib ------
It doesn't seem like there is enough empty space. Continue anyway.Added LC_LOAD_DYLIB to /Applications/WeChat.app/Contents/MacOS/WeChat
------ Add Codesign ------
Execute command: codesign --force --deep --sign - /Applications/WeChat.app/Contents/MacOS/WeChat
Install failed: Execute command: codesign --force --deep --sign - /Applications/WeChat.app/Contents/MacOS/WeChat failed: {
    NSAppleScriptErrorAppName = "wechattweak-cli";
    NSAppleScriptErrorBriefMessage = "/Applications/WeChat.app/Contents/MacOS/WeChat: resource fork, Finder information, or similar detritus not allowed";
    NSAppleScriptErrorMessage = "/Applications/WeChat.app/Contents/MacOS/WeChat: resource fork, Finder information, or similar detritus not allowed";
    NSAppleScriptErrorNumber = 1;
    NSAppleScriptErrorRange = "NSRange: {0, 97}";
}

**Comment by wjy5178** [comment]
我是同样的错误，现在
<img width="260" alt="image" src="https://user-images.githubusercontent.com/12595606/235852582-ec940e37-2bc0-4cba-8907-4eb7e68aeaf4.png">
<img width="489" alt="image" src="https://user-images.githubusercontent.com/12595606/235852681-af3ae632-5c51-4f9f-8480-5386f98cb87b.png">
