### ISSUE TITLE
截图给了权限但是一直提示

### ISSUE THREAD

**Issue by gm-fire** [sunnyyoung/WeChatTweak-CLI#34]
macos m1 12.3.1
wechat 3.4.0 (21723)
wechattweak-cli 1.3.1
系统-隐私-屏幕录制 已经添加了微信,但是每次截图都提醒没有权限
5.13 brew 安装的

**Comment by Duhonghao** [comment]
+1

**Comment by Knight90** [comment]
在“安全性和隐私”找到“屏幕录制”，解锁后先把微信删除，在用+添加回来

这种方法试试看

**Comment by Duhonghao** [comment]
确实可以解决！感谢！
