### ISSUE TITLE
1.4版本brew没有?

### ISSUE THREAD

**Issue by ops-xu** [Sunnyyoung/WeChatTweak-CLI#39]
brew安装后, version是1.3.1, 看github已经1.4了, 但是install也没有更新到1.4, 重新brew安装也还是1.3.1

**Comment by chenrui333** [comment]
这个就是 1.4?
https://github.com/Sunnyyoung/homebrew-repo/blob/master/Casks/wechattweak-cli.rb#L2

**Comment by ops-xu** [comment]
brew安装的wechatttweak-cli是1.4版本,但是wechatttweak-cli install后, wechatttweak-cli version显示的1.3.1

**Comment by Sunnyyoung** [comment]
`wechattweak-cli version` 指的是获取 WeChatTweak 版本，查看 `wechattweak-cli` 版本请用 `brew info wechattweak-cli`
