### ISSUE TITLE
商店最新版安装报错

### ISSUE THREAD

**Issue by alterem** [Sunnyyoung/WeChatTweak-CLI#40]
------ Download ------
------ Unzip ------
Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS
Install failed: Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS failed: {
    NSAppleScriptErrorAppName = "wechattweak-cli";
           No such file or directory";checkdir:  cannot create extraction directory: /Applications/WeChat.app/Contents/MacOS
           No such file or directory";dir:  cannot create extraction directory: /Applications/WeChat.app/Contents/MacOS
    NSAppleScriptErrorNumber = 2;
    NSAppleScriptErrorRange = "NSRange: {0, 157}";
}

**Comment by Silence566** [comment]
<img width="990" alt="image" src="https://user-images.githubusercontent.com/43640628/200827118-fad42e91-13fb-47ba-afc4-6c28b857647b.png">
没问题呀

**Comment by alterem** [comment]
> <img alt="image" width="990" src="https://user-images.githubusercontent.com/43640628/200827118-fad42e91-13fb-47ba-afc4-6c28b857647b.png">
> 
> 没问题呀

最新版本微信和最新版本macOS吗

**Comment by alterem** [comment]
/Applications/ 底下只有 微信.app 没有 WeChat.app rename 后，问题解决
