### ISSUE TITLE
macOS升级到13.0版本后，好像不能使用了？

### ISSUE THREAD

**Issue by wuming-g** [sunnyyoung/WeChatTweak-CLI#41]
请问大神有什么解决方案吗？

**Comment by jiumengs** [comment]
我的13可以用 但是我刚刚微信升级到Version. 3.6.0 (24192)就不能用了

**Comment by wuming-g** [comment]
------ Download ------
------ Unzip ------
Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS
Install failed: Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS failed: {
    NSAppleScriptErrorAppName = "wechattweak-cli";
    NSAppleScriptErrorBriefMessage = "checkdir error:  cannot create /Applications/WeChat.app/Content                 unable to process WeChatTweak.framework/Versions/A/Resources/Base.lproj/TweakPrefere                 unable to process WeChatTweak.framework/Versions/A/Resources/Base.lproj/TweakPrefere                 unable to process WeChatTweak.framework/Versions/A/Resources/Base.lproj/TweakPrefere                 unable to process WeChatTweak.framework/Versions/A/Resources/en.lproj/Localizable.st                 unable to process WeChatTweak.framework/Versions/A/Resources/en.lproj/TweakPreferenc                 unable to process WeChatTweak.framework/Versions/A/Resources/zh-Hans.lproj/Localizab                 unable to process WeChatTweak.framework/Versions/A/Resources/zh-Hans.lproj/TweakPref                 unable to process WeChatTweak.framework/Versions/A/Resources/zh-Hant.lproj/Localizab                 unable to process WeChatTweak.framework/Versions/A/Resources/zh-Hant.lproj/TweakPref                 unable to process WeChatTweak.framework/WeChatTweak.";WeChatTweak.framework
    NSAppleScriptErrorMessage = "checkdir error:  cannot create /Applications/WeChat.app/Contents/Mac                 unable to process WeChatTweak.framework/Versions/A/Resources/Base.lproj/TweakPrefere                 unable to process WeChatTweak.framework/Versions/A/Resources/Base.lproj/TweakPrefere                 unable to process WeChatTweak.framework/Versions/A/Resources/Base.lproj/TweakPrefere                 unable to process WeChatTweak.framework/Versions/A/Resources/en.lproj/Localizable.st                 unable to process WeChatTweak.framework/Versions/A/Resources/en.lproj/TweakPreferenc                 unable to process WeChatTweak.framework/Versions/A/Resources/zh-Hans.lproj/Localizab                 unable to process WeChatTweak.framework/Versions/A/Resources/zh-Hans.lproj/TweakPref                 unable to process WeChatTweak.framework/Versions/A/Resources/zh-Hant.lproj/Localizab                 unable to process WeChatTweak.framework/Versions/A/Resources/zh-Hant.lproj/TweakPref                 unable to process WeChatTweak.framework/WeChatTweak.";WeChatTweak.framework
    NSAppleScriptErrorNumber = 2;
    NSAppleScriptErrorRange = "NSRange: {0, 157}";
}

**Comment by wuming-g** [comment]
上面是更新时的错误提示。

我昨晚升级macOS系统到13.0.1，仍然出错。
微信版本号：Version.3.6.0(24191)

**Comment by jiumengs** [comment]
我现在正在重新安装。期待我的好消息

**Comment by jiumengs** [comment]
重新安装了也不行 等待作者更新吧
![image](https://user-images.githubusercontent.com/39983417/200992779-a27a5b6e-6c87-41ec-b6cd-c30731332eec.png)

**Comment by wuming-g** [comment]
希望能找到成功的方法

旧梦 ***@***.***> 于 2022年11月10日周四 11:17写道：

**Comment by simple4wan** [comment]
系统设置-隐私与安全性-App管理-iTerm(终端)  选中 就可以了。

**Comment by wuming-g** [comment]
感谢楼上朋友！

按你说的方法，已经搞定！

------ Download ------
------ Unzip ------
Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS
------ Backup ------
Created WeChat.bak...
------ Remove Codesign ------
Execute command: codesign --remove-sign /Applications/WeChat.app/Contents/MacOS/WeChat
------ Insert Dylib ------
Binary is a fat binary with 2 archs.
Added LC_LOAD_DYLIB to all archs in /Applications/WeChat.app/Contents/MacOS/WeChat
------ Add Codesign ------
Execute command: codesign --force --deep --sign - /Applications/WeChat.app/Contents/MacOS/WeChat
Install success!

**Comment by zhangcheng** [comment]
Needs to turn on this toggle (MacOS Ventura).

<img width="475" alt="image" src="https://user-images.githubusercontent.com/189283/202979483-51297017-e626-42f9-8583-b679262b0b56.png">

**Comment by waynecjx** [comment]
>不是微信weak-cli 本身的锅，是MacOS 13（Ventura）更新了权限管理的影响，需要打开如图这个开关。>> <img alt="图像" width="475" src="https://user-images.githubusercontent.com/189283/202979483-51297017-e626-42f9-8583-b679262b0b56.png">
能安装成功，但是好像并没有生效，设置里没有选项，也不能多开和拦截

**Comment by chenrui333** [comment]
> 系统设置-隐私与安全性-App管理-iTerm(终端) 选中 就可以了。

这个方法就可以

**Comment by HelloXiaoxi** [comment]
13.0.1，截屏功能不能用，总是提示要打开权限。如何解决呢？

**Comment by zhangcheng** [comment]
> 能安装成功，但是好像并没有生效，设置里没有选项，也不能多开和拦截

能安装成功，就说明这个权限管理方面是 ok 的了。
WeChatTweak 功能没有生效，应该是其他的原因。

**Comment by shubibin** [comment]
> > 系统设置-隐私与安全-App管理-iTerm(终端)选中就可以了。
> 
> 这个方法就可以

可以安装了，但是防撤回用不了

**Comment by shubibin** [comment]
> > 能安装成功，但是好像并没有生效，设置里没有选项，也不能多开和拦截
> 
> 能安装成功，就说明这个权限管理方面是 ok 的了。 WeChatTweak 功能没有生效，应该是其他的原因。

好吧，那就搞不懂为啥了，可以双开了，但是防撤回有些不太好使了

**Comment by Chester-Chen** [comment]
> 系统设置-隐私与安全性-App管理-iTerm(终端) 选中 就可以了。

可以解决，🙏。

**Comment by 0utman1** [comment]
` sudo wechattweak-cli install
Password:
------ Download ------
------ Unzip ------
Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS
------ Backup ------
WeChat.bak exists, skip it...
------ Remove Codesign ------
Execute command: codesign --remove-sign /Applications/WeChat.app/Contents/MacOS/WeChat
------ Insert Dylib ------
Binary is a fat binary with 2 archs.
Binary already contains a load command for that dylib. Skip it.
Binary already contains a load command for that dylib. Skip it.
Added LC_LOAD_DYLIB to all archs in /Applications/WeChat.app/Contents/MacOS/WeChat
------ Add Codesign ------
Execute command: codesign --force --deep --sign - /Applications/WeChat.app/Contents/MacOS/WeChat
Install failed: Execute command: codesign --force --deep --sign - /Applications/WeChat.app/Contents/MacOS/WeChat failed: {
    NSAppleScriptErrorAppName = "wechattweak-cli";
    NSAppleScriptErrorBriefMessage = "/Applications/WeChat.app/Contents/MacOS/WeIn subcomponent: /Applications/WeChat.app/Contents/MacOS/WeChat alias";d
    NSAppleScriptErrorMessage = "/Applications/WeChat.app/Contents/MacOS/WeChat:In subcomponent: /Applications/WeChat.app/Contents/MacOS/WeChat alias";
    NSAppleScriptErrorNumber = 1;
    NSAppleScriptErrorRange = "NSRange: {0, 97}";
}` 
给了App Managent和Full disk access两个权限也不行呢

**Comment by 0utman1** [comment]
> ` sudo wechattweak-cli install Password: ------ Download ------ ------ Unzip ------ Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS ------ Backup ------ WeChat.bak exists, skip it... ------ Remove Codesign ------ Execute command: codesign --remove-sign /Applications/WeChat.app/Contents/MacOS/WeChat ------ Insert Dylib ------ Binary is a fat binary with 2 archs. Binary already contains a load command for that dylib. Skip it. Binary already contains a load command for that dylib. Skip it. Added LC_LOAD_DYLIB to all archs in /Applications/WeChat.app/Contents/MacOS/WeChat ------ Add Codesign ------ Execute command: codesign --force --deep --sign - /Applications/WeChat.app/Contents/MacOS/WeChat Install failed: Execute command: codesign --force --deep --sign - /Applications/WeChat.app/Contents/MacOS/WeChat failed: { NSAppleScriptErrorAppName = "wechattweak-cli"; NSAppleScriptErrorBriefMessage = "/Applications/WeChat.app/Contents/MacOS/WeIn subcomponent: /Applications/WeChat.app/Contents/MacOS/WeChat alias";d NSAppleScriptErrorMessage = "/Applications/WeChat.app/Contents/MacOS/WeChat:In subcomponent: /Applications/WeChat.app/Contents/MacOS/WeChat alias"; NSAppleScriptErrorNumber = 1; NSAppleScriptErrorRange = "NSRange: {0, 97}"; }` 给了App Managent和Full disk access两个权限也不行呢

重新安装就好了，可能跟重复签名有关系？
