### ISSUE TITLE
新版微信无法安装

### ISSUE THREAD

**Issue by ChristmasZCY** [sunnyyoung/WeChatTweak-CLI#43]
<img width="1711" alt="image" src="https://user-images.githubusercontent.com/61818189/221095049-b20b44e9-43d0-464b-8aa4-58d0120f4f67.png">
<img width="586" alt="image" src="https://user-images.githubusercontent.com/61818189/221095112-0d5e29d2-6121-4427-b3c3-8c8ec3658b83.png">

**Comment by sunnyyoung** [comment]
请更新 1.4.0
