### ISSUE TITLE
提示这个问题？ 该如何修改网络

### ISSUE THREAD

**Issue by zhagsongcode** [sunnyyoung/WeChatTweak-CLI#44]
Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSErrorFailingURLStringKey=https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/latest/download/WeChatTweak.framework.zip, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDownloadTask <BFD6279E-3532-4E24-97EA-A50EE0DF468C>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDownloadTask <BFD6279E-3532-4E24-97EA-A50EE0DF468C>.<1>"
), NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/latest/download/WeChatTweak.framework.zip, NSUnderlyingError=0x7fd2385216a0 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9858, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9858}}, _kCFStreamErrorCodeKey=-9858}

**Comment by lc-Coco** [comment]
一样， 你解决了吗？

**Comment by zhagsongcode** [comment]
没有 感觉这个版本已经没用了


在 2023年4月6日 ***@***.***> 写道：


一样， 你解决了吗？

**Comment by henryyds** [comment]
没碰到这个问题，但是安装成功后插件无效

**Comment by sunnyyoung** [comment]
export HTTP_PROXY
