### ISSUE TITLE
请问新版是不是不能用了

### ISSUE THREAD

**Issue by henryyds** [sunnyyoung/WeChatTweak-CLI#45]
安装成功，但是微信里看不到

**Comment by henryyds** [comment]
有人吗

**Comment by dengmengmian** [comment]
估计不维护了,没有人用了,新版本装了不能多开了.我看51放假有空自己改下吧.

**Comment by henryyds** [comment]
> 估计不维护了,没有人用了,新版本装了不能多开了.我看51放假有空自己改下吧.

改了后求updte😭

**Comment by sunnyyoung** [comment]
@dengmengmian 刚更新

**Comment by sunnyyoung** [comment]
@henryyds 上日志上截图

**Comment by henryyds** [comment]
> @henryyds 上日志上截图

安装是没问题的，日志正常，就是没有小助手窗口而已

**Comment by sunnyyoung** [comment]
@henryyds 什么叫小助手窗口

**Comment by henryyds** [comment]
> @henryyds 什么叫小助手窗口

就是打开微信后看不到小助手了，和楼上老哥问题一样

**Comment by sunnyyoung** [comment]
@henryyds 本项目从来没有叫过/出现过小助手，所有设置都在 Settings 页面，你是不是串台了？

**Comment by henryyds** [comment]
> @henryyds 本项目从来没有叫过/出现过小助手，所有设置都在 Settings 页面，你是不是串台了？

我打错了不好意思，反正就是安装成功，setting里面什么都没有

**Comment by sunnyyoung** [comment]
安装完 cli，执行 `sudo wechattweak-cli install` 了吗

**Comment by lw404-ai** [comment]
您好 我执行sudo wechattweak-cli install出现如下错误，怎么解决？
```
Install failed: Execute command: codesign --remove-sign /Applications/WeChat.app/Contents/MacOS/WeChat failed: {
    NSAppleScriptErrorAppName = "wechattweak-cli";
Run with --help for more information.";-sign is required
Run with --help for more information."; is required
    NSAppleScriptErrorNumber = 106;
    NSAppleScriptErrorRange = "NSRange: {0, 87}";
}
```

**Comment by mushanzi1216** [comment]
> 您好 我执行sudo wechattweak-cli install出现如下错误，怎么解决？
> 
> ```
> Install failed: Execute command: codesign --remove-sign /Applications/WeChat.app/Contents/MacOS/WeChat failed: {
>     NSAppleScriptErrorAppName = "wechattweak-cli";
> Run with --help for more information.";-sign is required
> Run with --help for more information."; is required
>     NSAppleScriptErrorNumber = 106;
>     NSAppleScriptErrorRange = "NSRange: {0, 87}";
> }
> ```

请问老哥问题解决了嘛 我也遇到这个问题了
<img width="544" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-CLI/assets/6134260/6911b324-2fe5-403a-8ee7-1cd0f02a0663">

**Comment by mushanzi1216** [comment]
> 您好 我执行sudo wechattweak-cli install出现如下错误，怎么解决？
> 
> ```
> Install failed: Execute command: codesign --remove-sign /Applications/WeChat.app/Contents/MacOS/WeChat failed: {
>     NSAppleScriptErrorAppName = "wechattweak-cli";
> Run with --help for more information.";-sign is required
> Run with --help for more information."; is required
>     NSAppleScriptErrorNumber = 106;
>     NSAppleScriptErrorRange = "NSRange: {0, 87}";
> }
> ```

看下这个issue https://github.com/sunnyyoung/WeChatTweak-CLI/issues/41  是需要设置item2

**Comment by sunnyyoung** [comment]
[1.3.5](https://github.com/sunnyyoung/WeChatTweak-macOS/releases) 版本已更新支持
