### ISSUE TITLE
支持默认浏览器打开

### ISSUE THREAD

**Issue by icpd** [sunnyyoung/WeChatTweak-CLI#48]
新版微信只能内置浏览器打开，实在令人不悦，作者可否有方案修改为默认浏览器打开？

**Comment by henryyds** [comment]
好问题，我也想问

**Comment by henryyds** [comment]
> 新版微信只能内置浏览器打开，实在令人不悦，作者可否有方案修改为默认浏览器打开？

兄弟找到解决方案了吗

**Comment by henryyds** [comment]
> 新版微信只能内置浏览器打开，实在令人不悦，作者可否有方案修改为默认浏览器打开？

找到了 输入：recover

**Comment by henryyds** [comment]
> 新版微信只能内置浏览器打开，实在令人不悦，作者可否有方案修改为默认浏览器打开？

网上设置的方法失效了
