### ISSUE TITLE
最新版微信失效

### ISSUE THREAD

**Issue by henryyds** [sunnyyoung/WeChatTweak-CLI#49]
Version 3.8.0 (26239)能看到插件和设置，但是失去拦截功能，请问能否修复，谢谢

**Comment by FaiChou** [comment]
<img width="583" alt="WechatIMG65870" src="https://github.com/sunnyyoung/WeChatTweak-CLI/assets/18500846/34ee8e76-b8b7-4f1e-a64d-c8c6628b4d7a">

+1 新版本失效了

**Comment by henryyds** [comment]
还有update吗

**Comment by AndrewTseZhou** [comment]
失效了 求修复

**Comment by henryyds** [comment]
> 失效了 求修复

你是升级后失效了吗，还是旧版本也不行

**Comment by chenzhiguo** [comment]
附议

**Comment by AndrewTseZhou** [comment]
> > 失效了 求修复
> 
> 你是升级后失效了吗，还是旧版本也不行

升级后失效的

**Comment by icpd** [comment]
+1, 突然发现撤回用不了了

**Comment by callmepopo** [comment]
3.7.1升级3.8后，重新安装无法使用。有设置页面，但是无效果。
以前升级后，重新安装都能正常使用。
请教各位如何能下载3.7.1的微信客户端

**Comment by NicholasLD** [comment]
+1

**Comment by sunnyyoung** [comment]
[1.3.5](https://github.com/sunnyyoung/WeChatTweak-macOS/releases) 版本已更新支持
