### ISSUE TITLE
新版3.8撤回没提示了 看不见谁撤回了 找了3.7版本各种重装也不行了

### ISSUE THREAD

**Issue by wu12734** [sunnyyoung/WeChatTweak-CLI#50]
<img width="340" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-CLI/assets/38997216/32ba16ea-f7fd-42fc-9717-78912f4d01ee">

**Comment by hsiaowei** [comment]
3.7版本可以的

**Comment by huihongzhou** [comment]
大佬啊 3.8 不行了啊！help

**Comment by sunnyyoung** [comment]
1.3.5 版本已更新支持 https://github.com/sunnyyoung/WeChatTweak-macOS/releases
