### ISSUE TITLE
最新版本 3.8.1 失效

### ISSUE THREAD

**Issue by henryyds** [sunnyyoung/WeChatTweak-CLI#53]
rt，为什么现在每个新版本都失效。
感激不尽

**Comment by imruxin** [comment]
确认失效+1

**Comment by AndrewTseZhou** [comment]
+1

**Comment by sunnyyoung** [comment]
请更新 1.4.0

**Comment by imruxin** [comment]
我看了下更新文件的下载路径是上 1.5，wechattweak-cli version 显示的是 1.4。

然后，更新后，实测直接 sudo wechattweak-cli install 是无效的，得先 sudo wechattweak-cli uninstall 一下，然后再 sudo wechattweak-cli install 这样才正常了。
