### ISSUE TITLE
MacOS14 双开无限弹窗

### ISSUE THREAD

**Issue by xhatt** [sunnyyoung/WeChatTweak-CLI#58]
<img width="292" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-CLI/assets/44392078/a9b783a0-d292-489c-a3b4-767e9a8ac0db">

<img width="336" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-CLI/assets/44392078/a7b48b2c-4c07-4f4f-bd2c-3e886d2e25dc">

**Comment by DreamXiao** [comment]
目前我添加了完全磁盘访问权限，这样试了下ok了。遇到微信自动更新了插件失效了。重新安装了插件也是一直弹窗。后来加了访问权限。

**Comment by xhatt** [comment]
> 目前我添加了完全磁盘访问权限，这样试了下ok了。 遇到微信自动更新了插件失效了，重新安装了插件也是一直弹窗。后来加了访问权限才行。 ![Xnip2023-10-18_01-03-46](https://user-images.githubusercontent.com/4948854/275920191-11006475-75cc-4d89-af6d-5aa168f66995.jpg)
多谢大佬解答！加了就好了

**Comment by DreamXiao** [comment]
完蛋。wx升级3.8.5以后又不行了 加了权限 开第二个wx的时候还是一直弹窗了。权限取消重新加也不行。。。
<img width="509" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-CLI/assets/4948854/5a1684f1-8558-4c6c-b2e8-ae40153c3b94">
