### ISSUE TITLE
 brew install sunnyyoung/repo/wechattweak-cli 报错

### ISSUE THREAD

**Issue by ghl116** [Sunnyyoung/WeChatTweak-CLI#6]
➜  WeChatTweak-macOS git:(master) brew install sunnyyoung/repo/wechattweak-cli

Error: No available formula with the name "sunnyyoung/repo/wechattweak-cli"
==> Searching for a previously deleted formula (in the last month)...
Warning: sunnyyoung/repo is shallow clone. To get complete history run:
  git -C "$(brew --repo sunnyyoung/repo)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.

**Comment by Sunnyyoung** [comment]
`git -C "$(brew --repo sunnyyoung/repo)" fetch --unshallow`

**Comment by ghl116** [comment]
1. brew install sunnyyoung/repo/wechattweak-cli安装成功，
 2. sudo wechattweak-cli --install 安装失败
报错如下：

➜  homebrew-core git:(master) brew reinstall sunnyyoung/repo/wechattweak-cli
Warning: You are using macOS 10.13.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.

==> Downloading https://github.com/Sunnyyoung/WeChatTweak-CLI/releases/download/1.2/wechattweak-cli
Already downloaded: /Users/gaohailong/Library/Caches/Homebrew/downloads/f9a25cad1abc6ec535a537b726546b038ccaae209f36a2d74e188049370baf4e--wechattweak-cli
All formula dependencies satisfied.
==> Uninstalling Cask wechattweak-cli
==> Unlinking Binary '/usr/local/bin/wechattweak-cli'
==> Purging files for version 1.2 of Cask wechattweak-cli
==> Installing Cask wechattweak-cli
==> Linking Binary 'wechattweak-cli' to '/usr/local/bin/wechattweak-cli'
🍺  wechattweak-cli was successfully installed!
➜  homebrew-core git:(master) wechattweak-cli --install
Install failed: Please run with `sudo`.
➜  homebrew-core git:(master) sudo wechattweak-cli --install
Password:
------ Backup ------
Created WeChat.bak...
------ Download ------
Install failed: Download failed with error: Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x7f8d8d41c490 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/latest/download/WeChatTweak.framework.zip, NSErrorFailingURLKey=https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/latest/download/WeChatTweak.framework.zip, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.}

**Comment by Sunnyyoung** [comment]
下再失败了，网络问题

**Comment by ghl116** [comment]
> 下再失败了，网络问题

有离线版本吗？或者如何解决网络问题，我用是的电信200M的宽带啊

**Comment by ghl116** [comment]
sudo wechattweak-cli --install
Password:
------ Backup ------
WeChat.bak exists, skip it...
------ Download ------
Install failed: Download failed with error: Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x7f834e60b0a0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/latest/download/WeChatTweak.framework.zip, NSErrorFailingURLKey=https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/latest/download/WeChatTweak.framework.zip, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.}

**Comment by ghl116** [comment]
能不能搞个gitee版本啊？

**Comment by Ale-cc** [comment]
解决办法
--
brew 安装失败：LibreSSL SSL_connect: SSL_ERROR_SYSCALL
https://juejin.cn/post/6987392117236564005

**Comment by jbsn573** [comment]
$ brew install sunnyyoung/repo/wechattweak-cli
zsh: command not found: $
