### ISSUE TITLE
安装之后，登陆微信、使用微信特别卡顿

### ISSUE THREAD

**Issue by BlackSirBAI** [sunnyyoung/WeChatTweak-CLI#65]
1、安装插件后，每次打开微信提示“获取文稿权限”，
       1.1 不允许时：扫码登录，无历史记录，和一个新微信一样
       1.2 允许时：可正常登陆，历史记录正常
       1.3 登陆时长不固定：大于1分钟
2、微信登陆成功后，特别卡顿：
      2.1  切换聊天窗口：延迟10s左右，还有完全卡死的现象
      2.2 进入聊天窗口时，滚动查看消息，卡顿，基本无法正常浏览
      2.3 打开图片、视频时：卡顿，延迟30s左右，打开后还会卡顿10s左右才会显示高清

系统版本：14.5 (23F79)
处理器：四核Intel Core i7
内存：15G

**Comment by JeremyXING** [comment]
m1 同样的问题，感觉是升级了14.5后出现的

**Comment by woshizhangxiaohao** [comment]
我没有这个问题。我是m1，macOS14.4.1版本 微信3.8.8.18版本

**Comment by Tassel-s** [comment]
我也遇到了这个问题,升级到Version. 3.8.8 (28486)版本后出现的
系统版本：14.5 (23F79)
处理器：Apple M1 Pro
内存：16 GB

**Comment by JeremyXING** [comment]
> 我这边解决了,参考了大佬的另一个项目的issue：
> 
> 1. 退出微信
> 2. uninstall&install
> 3. 设置-隐私与安全性-完全磁盘访问权限 删除&重新添加微信
> 4. 重新打开微信

确实可以了，感谢。完全磁盘访问权限里没有微信，我添加了问题解决。

**Comment by CfgiCat** [comment]
> 我这边解决了,参考了大佬的另一个项目的issue：
> 
> 1. 退出微信
> 2. uninstall&install
> 3. 设置-隐私与安全性-完全磁盘访问权限 删除&重新添加微信
> 4. 重新打开微信

确实有用，快多了

**Comment by BlackSirBAI** [comment]
1、退出微信
2、uninstall&install
3、设置-隐私与安全性-完全磁盘访问权限 删除&重新添加微信
4、重新打开微信
